In [1]:
import face_recognition
import cv2
import numpy as np

In [2]:
# Loading all the images
img_hrithik1 = face_recognition.load_image_file('imagedetec/Hrithik-Roshan-1.jpg') #bgr #returns an array representation of images
img_hrithik1 = cv2.cvtColor(img_hrithik1, cv2.COLOR_BGR2RGB) # BGR TO RGB
img_hrithik2 = face_recognition.load_image_file('imagedetec/Ratan_tata.jpg')
img_hrithik2 = cv2.cvtColor(img_hrithik2, cv2.COLOR_BGR2RGB)
img_ratantata = face_recognition.load_image_file('imagedetec/Ratan_tata.jpg')
img_ratantata = cv2.cvtColor(img_ratantata, cv2.COLOR_BGR2RGB)

In [3]:
img_hrithik1.shape, img_hrithik2.shape, img_ratantata.shape

((563, 750, 3), (702, 512, 3), (702, 512, 3))

In [4]:
# locating face location in train image
face_loc = face_recognition.face_locations(img_hrithik1)[0]
hrithik_encod = face_recognition.face_encodings(img_hrithik1)[0]

In [5]:
face_loc, hrithik_encod

((142, 527, 409, 260),
 array([-9.82032418e-02,  1.23916805e-01,  1.01674996e-01, -8.27004910e-02,
        -1.20795101e-01,  8.33639130e-03, -4.58095968e-02, -7.79753923e-02,
         1.03093952e-01,  1.98765658e-04,  1.34342775e-01, -1.38080642e-02,
        -2.72528946e-01,  9.58857387e-02, -2.18442157e-02,  6.77506626e-02,
        -1.95460230e-01, -1.07855462e-01, -9.78895202e-02, -4.80119623e-02,
        -1.48690585e-02,  1.01422735e-01, -1.38067054e-02,  5.22496700e-02,
        -6.71409667e-02, -2.95457691e-01, -7.72568956e-02, -1.03088774e-01,
         9.85174924e-02, -5.06266281e-02,  1.43722845e-02, -1.65149178e-02,
        -2.32358575e-01, -8.34491476e-02,  1.13417497e-02, -4.48134169e-03,
        -3.40195708e-02, -6.65993616e-02,  1.91092476e-01,  2.03121938e-02,
        -8.79732892e-02,  2.89051477e-02,  1.34244606e-01,  2.94710666e-01,
         9.52666923e-02,  1.12161301e-01,  3.34046185e-02,  2.84326635e-03,
         8.04169029e-02, -2.46345416e-01,  1.38993889e-01,  1.029

In [6]:
# Since we have now the face location coordinates of train image lets draw a rectangle around them using opencv
cv2.rectangle(img_hrithik1,(face_loc[3],face_loc[0]),(face_loc[1],face_loc[2]),(0,255,0),3)

array([[[155, 138, 129],
        [155, 138, 129],
        [155, 138, 129],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       [[154, 137, 128],
        [154, 137, 128],
        [154, 137, 128],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       [[153, 136, 127],
        [153, 136, 127],
        [154, 137, 128],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       ...,

       [[ 97,  71,  64],
        [ 94,  68,  61],
        [ 84,  61,  53],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]],

       [[ 81,  57,  51],
        [ 81,  57,  51],
        [ 76,  54,  48],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]],

       [[ 70,  46,  40],
        [ 73,  49,  43],
        [ 72,  50,  44],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]]

In [7]:
# locating face location, encoding the test image then putting the rectangle arounf the face location in test image
test_loc = face_recognition.face_locations(img_hrithik2)[0]
test_encod = face_recognition.face_encodings(img_hrithik2)[0]
cv2.rectangle(img_hrithik2,(test_loc[3],test_loc[0]),(test_loc[1],test_loc[2]),(0,255,0),3)

array([[[101, 134, 143],
        [102, 138, 144],
        [104, 136, 147],
        ...,
        [113, 143, 154],
        [115, 147, 158],
        [114, 148, 161]],

       [[ 99, 132, 141],
        [ 96, 129, 138],
        [ 98, 133, 143],
        ...,
        [113, 142, 156],
        [117, 149, 162],
        [115, 149, 162]],

       [[ 99, 132, 141],
        [ 96, 133, 137],
        [ 99, 131, 137],
        ...,
        [114, 145, 160],
        [121, 152, 167],
        [117, 151, 164]],

       ...,

       [[ 91, 117, 104],
        [ 88, 114, 101],
        [ 90, 110, 105],
        ...,
        [ 16,   8,   9],
        [ 16,   8,   8],
        [ 18,  11,   8]],

       [[ 86, 112, 112],
        [ 83, 115, 110],
        [ 88, 116, 117],
        ...,
        [  9,  10,   6],
        [ 10,  11,   9],
        [  9,  10,   8]],

       [[ 83, 111, 111],
        [ 82, 113, 112],
        [ 89, 118, 123],
        ...,
        [ 11,   9,   8],
        [ 11,   9,   8],
        [ 14,  10,   9]]

# Step 3 - Comparing the faces using their encodings

In [8]:
results = face_recognition.compare_faces([hrithik_encod], test_encod)

# if we want to check the face distance
facedis = face_recognition.face_distance([hrithik_encod], test_encod)

In [9]:
results, facedis

([False], array([0.80006904]))

In [10]:
# Putting the results on the required images using opencv
cv2.putText(img_hrithik2, str(results)+'  'str(round(facedis[0],2)), (100,100), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 3)

array([[[101, 134, 143],
        [102, 138, 144],
        [104, 136, 147],
        ...,
        [113, 143, 154],
        [115, 147, 158],
        [114, 148, 161]],

       [[ 99, 132, 141],
        [ 96, 129, 138],
        [ 98, 133, 143],
        ...,
        [113, 142, 156],
        [117, 149, 162],
        [115, 149, 162]],

       [[ 99, 132, 141],
        [ 96, 133, 137],
        [ 99, 131, 137],
        ...,
        [114, 145, 160],
        [121, 152, 167],
        [117, 151, 164]],

       ...,

       [[ 91, 117, 104],
        [ 88, 114, 101],
        [ 90, 110, 105],
        ...,
        [ 16,   8,   9],
        [ 16,   8,   8],
        [ 18,  11,   8]],

       [[ 86, 112, 112],
        [ 83, 115, 110],
        [ 88, 116, 117],
        ...,
        [  9,  10,   6],
        [ 10,  11,   9],
        [  9,  10,   8]],

       [[ 83, 111, 111],
        [ 82, 113, 112],
        [ 89, 118, 123],
        ...,
        [ 11,   9,   8],
        [ 11,   9,   8],
        [ 14,  10,   9]]

In [11]:
# viewing the images using opencv
cv2.imshow('1',img_hrithik1)
cv2.imshow('2',img_hrithik2)
cv2.imshow('3',img_ratantata)

cv2.waitKey(0) #always remember to include it when using cv2.imshow to view the iamges

-1